### ISSUE TITLE
Tooltips lack role=tooltip

### ISSUE THREAD

**Issue by t3chguy** [element-hq/compound#330]
# Platform

Web

# Description

![image](https://github.com/user-attachments/assets/d1700b57-b6d0-48d8-9e14-5004edf05d96)

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role says they should have

**Comment by robintown** [comment]
This is expected behavior: https://github.com/element-hq/compound-web/blob/945a3f5558e424053b15492aa8a877233fa54197/src/components/Tooltip/useTooltip.ts#L223

See https://zoebijl.github.io/apg-tooltip/#tooltip-main-label and https://sarahmhigley.com/writing/tooltips-in-wcag-21/ for more commentary on the `tooltip` role. It's a bit of a mess, but it's the Web platform's mess.
